apiVersion: v1
kind: Service
metadata:
  name: {{ include "db2.fullname" . }}
  labels:
    db.name: {{ include "db2.name" . }}
    helm.sh/chart: {{ include "db2.chart" . }}
    db.instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
  selector:
    db.name: {{ include "db2.name" . }}
    db.instance: {{ .Release.Name }}
